# Generated by Django 5.2.6 on 2025-09-07 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=255)),
                ('pickup', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('shipping', 'Shipping'), ('delivered', 'Delivered')], max_length=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time', models.DateTimeField()),
                ('proof_photo', models.ImageField(blank=True, null=True, upload_to='proofs/photos/')),
                ('proof_signature', models.ImageField(blank=True, null=True, upload_to='proofs/signatures/')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver')),
            ],
        ),
    ]
