# Generated by Django 5.2.6 on 2025-10-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mobileprofile',
            new_name='mobile_auth_phone_453826_idx',
            old_name='mobile_prof_phone_idx',
        ),
    ]
