# Generated by hand to enforce non-negative values and clean existing data
from django.db import migrations, models


def clamp_user_non_negative(apps, schema_editor):
    User = apps.get_model('users', 'User')
    # Set any negative values to zero prior to adding constraints
    User.objects.filter(total_rides__lt=0).update(total_rides=0)
    User.objects.filter(total_spent__lt=0).update(total_spent=0)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_status'),
    ]

    operations = [
        migrations.RunPython(clamp_user_non_negative, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(
                check=models.Q(('total_rides__gte', 0)),
                name='user_total_rides_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(
                check=models.Q(('total_spent__gte', 0)),
                name='user_total_spent_non_negative',
            ),
        ),
    ]


