# Generated by Django 5.2.6 on 2025-10-22 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_fix_status_choices_and_cleanup'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_status_allowed_values',
        ),
    ]
