# Generated by Django 5.2.6 on 2025-10-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_profile_fields'),
        ('users', '0007_remove_user_user_status_allowed_values'),
    ]

    operations = [
    ]
