# Generated by Django 5.2.6 on 2025-09-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending')], max_length=10)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('motorcycle', 'Motorcycle'), ('van', 'Van')], max_length=20)),
                ('license_status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('processing', 'Processing'), ('rejected', 'Rejected')], max_length=12)),
                ('rating', models.FloatField(default=0)),
                ('total_rides', models.PositiveIntegerField(default=0)),
                ('earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('online', models.BooleanField(default=False)),
                ('join_date', models.DateField()),
                ('last_active', models.DateTimeField()),
            ],
        ),
    ]
