# Generated by hand to enforce non-negative values and clean existing data
from django.db import migrations, models


def clamp_driver_non_negative(apps, schema_editor):
    Driver = apps.get_model('drivers', 'Driver')
    Driver.objects.filter(total_rides__lt=0).update(total_rides=0)
    Driver.objects.filter(earnings__lt=0).update(earnings=0)


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driverapplication'),
    ]

    operations = [
        migrations.RunPython(clamp_driver_non_negative, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.CheckConstraint(
                check=models.Q(('total_rides__gte', 0)),
                name='driver_total_rides_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.CheckConstraint(
                check=models.Q(('earnings__gte', 0)),
                name='driver_earnings_non_negative',
            ),
        ),
    ]


