# Generated by Django 5.2.6 on 2025-10-22 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_driverapplication_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverapplication',
            options={'ordering': ['-applied_at']},
        ),
    ]
