# Generated by Django 5.2.6 on 2025-10-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_add_profile_enhancements'),
        ('drivers', '0007_alter_driverapplication_options'),
    ]

    operations = [
    ]
