# Generated by Django 5.2.6 on 2025-09-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('driver_ios', 'Driver iOS'), ('driver_android', 'Driver Android')], max_length=20)),
                ('current', models.CharField(max_length=20)),
                ('latest', models.CharField(max_length=20)),
                ('users', models.CharField(max_length=10)),
                ('force_update', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GeoZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('multiplier', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('discount', 'Discount'), ('free_ride', 'Free Ride'), ('referral', 'Referral')], max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('usage', models.CharField(max_length=20)),
                ('expiry', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], max_length=10)),
            ],
        ),
    ]
